name: citchat
description: Cummunication with other people.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.19.3 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  flutter_chat_ui: ^1.6.6
  flutter_firebase_chat_core: ^1.6.4
  intl: ^0.18.0
  go_router: ^8.2.0
  google_fonts: ^4.0.4
  firebase_auth: ^4.6.3
  firebase_messaging: ^14.6.3
  firebase_ui_auth: ^1.4.3
  dynamic_color: ^1.6.5
  carousel_slider: ^4.2.1
  icons_plus: ^4.0.0
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  cloud_firestore: ^4.8.2
  encrypt: ^5.0.1
  hex: ^0.2.0
  bcrypt: ^1.1.3
  firebase_core: ^2.14.0
  loading_animation_widget: ^1.2.0+4
  shared_preferences: ^2.1.2
  firebase_storage: ^11.2.4
  permission_handler: ^10.4.0
  image_picker: ^1.0.0
  flutter_image_compress: ^2.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/
    - assets/images/avatar.jpg
    - assets/images/avatar-2.jpg
    - assets/images/avatar-3.jpg
    - assets/images/avatar-4.jpg
    - assets/images/avatar-5.jpg
    - assets/images/taman_kota.jpg
    - assets/images/taman_kota2.webp
    - assets/images/ava.jpg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
